import React from 'react'
import Goto_magazine from './Goto-magazine'

const Full_story_container = ({text,to}) => {
    return (
        <div className='full-story-container'>
            <div className='story-text'>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus ipsum dignissimos hic voluptatem alias iste similique, et quam reiciendis! Sit consequuntur quis eaque tempora necessitatibus placeat corrupti quia id cupiditate?
                Recusandae accusantium enim tenetur vitae magni perferendis officia, nam architecto repellat dignissimos officiis sed impedit unde saepe excepturi pariatur animi voluptates voluptatibus esse harum necessitatibus natus numquam. Provident, corporis iste!
                Odio fugit, incidunt eum ipsum optio illo, excepturi tempore facere ipsa ratione soluta sint ex alias nisi fuga non exercitationem maiores doloribus sequi, quis hic eos. Autem beatae alias adipisci!
                Ab magnam quas amet culpa perspiciatis eum, quia beatae laboriosam distinctio asperiores illo accusantium cum harum? Ipsam quod molestias ut, aut nihil illo, veritatis incidunt debitis at neque repellendus voluptatem.
                Ipsa exercitationem ullam, facere illum nulla a, cupiditate nesciunt fuga eaque explicabo deserunt, commodi repellat consequuntur ex quos minus inventore! Aperiam provident dolorum, inventore ex corporis vero beatae voluptas. Vero!
                Inventore minima animi facilis magni pariatur, voluptatum, magnam alias voluptates culpa eius voluptatibus molestias nulla illum. Excepturi, similique quasi laudantium dicta, perspiciatis ducimus beatae necessitatibus exercitationem officia officiis temporibus amet.
                Accusantium possimus quibusdam eligendi natus tempore quia culpa! Eligendi modi vitae incidunt, ut iusto architecto iure beatae exercitationem maxime rem iste nemo impedit inventore libero! Dolores laboriosam nihil dolor error!
                Eos veniam voluptate aliquid temporibus. Ullam vel illo ratione incidunt, magni deleniti officia hic exercitationem itaque voluptatum unde? Doloribus provident eos rem quo aperiam architecto expedita repellat optio impedit. A!
                Sint libero in pariatur sapiente corporis quidem delectus neque numquam ad, ratione distinctio illum possimus, omnis non similique aperiam, hic fugiat. Aspernatur eius, commodi autem vel itaque ut voluptas voluptatibus!
                Dolor harum ipsa atque voluptas aliquid. Tempora tempore architecto exercitationem necessitatibus, quasi natus eveniet ab est accusantium harum mollitia eligendi corrupti eos corporis unde recusandae possimus nam placeat cum dolores!
                Dolores, id pariatur fugiat, repellat architecto hic animi eaque harum debitis laborum incidunt officia natus minima est. Modi, quos. Adipisci porro repellat consequatur quas blanditiis repellendus alias fugit maxime quidem.
                Nulla id ratione veritatis. Molestiae iste harum impedit. Iste obcaecati minus recusandae consequuntur debitis, illo veniam error repellendus. Quos, laborum. Debitis facilis vel, illo eum expedita itaque soluta aliquid praesentium?
                Quo maxime consequatur, iste quod quam odio sapiente excepturi repudiandae dolorum? Quae earum et, molestiae enim, explicabo adipisci repellendus suscipit eos voluptas doloremque distinctio facere aut fuga, quasi quis. Deserunt.
                Soluta explicabo incidunt assumenda, provident eaque harum magni enim earum illum? Corrupti ipsum modi sed voluptate voluptas a, similique ducimus fugiat ad minus debitis deleniti ratione dolore, doloremque earum iusto.
                Dolores at aut nemo ex placeat fuga blanditiis voluptatibus sit, tenetur ab eveniet, voluptates numquam consectetur facere nobis modi dolor eligendi assumenda maiores dolorum distinctio esse quod corporis! Iusto, perferendis.
                Eveniet quo mollitia beatae laborum ipsam quasi doloremque aliquid? Officia nemo blanditiis ea ab laboriosam alias doloremque quod obcaecati quam doloribus eaque fugiat voluptate, distinctio deleniti omnis dignissimos libero. Neque.
                Temporibus, similique. Optio reprehenderit voluptatum magnam laborum nulla placeat rerum provident obcaecati sapiente sunt, aperiam atque ad beatae. Aliquid consequuntur deserunt ut dolor obcaecati cum ad et omnis delectus harum!
                Facilis sapiente accusantium ipsam fugit, sit commodi ea at, fuga non minus repellat quos molestiae natus unde voluptatibus quo molestias quam nulla perferendis sunt. Nisi a distinctio aperiam eligendi perferendis.
                Nemo numquam culpa veniam modi possimus voluptatem earum et repellendus reprehenderit optio ea perspiciatis autem voluptas, inventore unde amet excepturi maxime, officiis blanditiis laboriosam facilis, obcaecati esse molestiae. Error, praesentium.
                Numquam vitae quae dignissimos molestiae voluptatum, obcaecati, adipisci saepe distinctio enim eligendi at, tenetur nostrum officia quasi. Voluptas unde doloremque officia repellat doloribus labore atque quia rerum, recusandae, vitae sapiente.
                Cupiditate odio impedit nemo voluptates voluptate distinctio voluptatibus asperiores quia provident tempora quos aperiam dolores, corporis non magnam temporibus, sint modi saepe dignissimos. Debitis, error aspernatur. Nulla dignissimos reiciendis pariatur.
                Ullam qui voluptas, quidem numquam neque facilis deleniti laborum voluptatum deserunt nam, illo recusandae aspernatur nemo soluta architecto sunt asperiores consectetur reprehenderit incidunt in. Mollitia a nihil beatae quod natus?
                Tempora ullam non illum aperiam cum totam eveniet ipsum vero ducimus, harum porro quidem ea. Sequi obcaecati aliquid distinctio veniam dignissimos assumenda sed nemo? Eius nemo eaque sit exercitationem cupiditate.
                Est ut eligendi, dignissimos fuga repudiandae accusantium illo perferendis facilis eveniet et commodi corrupti eum reiciendis maiores, ratione obcaecati nostrum iste vero sit quibusdam aliquid enim porro rerum? Quas, saepe.
                Quos eos nostrum, harum accusantium, aliquam excepturi quia in aut rerum at, velit quas accusamus! Quae, et reiciendis sint maxime fuga non natus enim, nesciunt eos perferendis, repudiandae eligendi eius.
                Nulla expedita molestiae maxime, excepturi suscipit itaque asperiores deleniti perspiciatis quibusdam voluptas officia delectus ea animi, incidunt earum laudantium eius aliquam sapiente culpa consequuntur architecto tempore sunt, quisquam quae. Sunt?
                Sed ullam, quasi molestias alias ipsum iste. Animi eius quos labore, earum eaque nisi aspernatur? Optio possimus dolor voluptas obcaecati error illum, consequatur sed similique. Ex, quidem est. Tempore, repudiandae!
                Iusto at, atque vel ea consequatur numquam praesentium quasi, odio iure officiis animi, maxime eveniet expedita et sed doloremque ipsum! Mollitia et natus reiciendis quo eius, itaque corporis. Officiis, officia?
                Debitis inventore pariatur accusamus ex neque ducimus quam, sint expedita quos ut dolore nulla sequi impedit praesentium. Iusto amet dicta eaque ad quasi officia ullam! Minima at enim consequatur sit!
                Inventore, rem optio. Illo animi eum beatae aliquid delectus quidem molestias quae optio qui! Pariatur deserunt velit iure officia quisquam fugiat eum vitae impedit, iste illum sequi aspernatur eveniet error.
                Architecto, magni vel, dignissimos reiciendis, distinctio minima iste libero nisi aspernatur vero dolorum molestiae ipsam harum aperiam nihil autem rerum. Doloribus aliquid odit corrupti. Obcaecati sunt hic repellendus earum aspernatur!
                Asperiores nisi quos, iste qui nulla earum blanditiis eveniet expedita dolorum. Quas at dolorum ipsam dolorem, amet quaerat, ad modi cumque sit deserunt unde assumenda consequatur vero perspiciatis impedit fugiat.
                Nisi itaque nulla hic, earum sed nostrum dolor commodi cum unde fugit possimus iste aperiam, quis vero dolorem sunt est? Officiis quod neque, cum eligendi eveniet earum. Deserunt, autem consequatur!
                Beatae molestias velit cupiditate fugit, laudantium perspiciatis ullam quae reiciendis facere ea quod dolore quisquam consequuntur. Quos et vitae deserunt, temporibus adipisci, vero consequuntur tempora eius dolorum eum, praesentium necessitatibus.
                Laboriosam amet repellat dolores maxime. Odio blanditiis alias perferendis eum rem eius, quos accusantium repudiandae assumenda rerum dicta, voluptate ipsam commodi eligendi vel distinctio. Dolores dignissimos id eligendi suscipit quaerat.
                Amet, a commodi. Laudantium, enim voluptatem voluptatum dolor illum nemo commodi voluptatibus officiis laborum expedita animi veniam ab dolorum, debitis quia similique totam fugiat assumenda laboriosam! Aperiam voluptatem inventore maiores.
                Minima nesciunt, maxime ex facere dolorem minus blanditiis laboriosam, illo officiis tempora eos reprehenderit sunt ea quisquam sapiente mollitia voluptate natus, porro a repellendus labore sed ducimus voluptatibus. Accusamus, rem?
                Quia cumque accusamus rerum eius ea corporis, ex nihil qui saepe ratione provident dignissimos rem debitis culpa, aspernatur perspiciatis, veritatis aut sit consequuntur iure ipsum nemo. Accusantium illum dolorum sequi?
                Laboriosam sunt, nesciunt assumenda praesentium non quod quae eum saepe sapiente modi molestias facere cum, incidunt, beatae nisi alias quo tempora enim nulla id aspernatur aliquam. Enim iste quisquam quod.
                Aliquam perspiciatis illum totam, adipisci quos reiciendis ex nihil quidem nam. Unde repellendus repudiandae necessitatibus nesciunt dolorum esse dolorem! Iure sequi tempore laborum repudiandae, reprehenderit illo distinctio aliquid sapiente assumenda?
                Temporibus suscipit reprehenderit, inventore voluptatum, praesentium unde, asperiores facilis laborum et eius officiis ullam vel iste. Quia voluptatum in, est aspernatur ex exercitationem sunt accusamus quisquam consequatur ipsum neque perferendis.
                Debitis, maxime autem. Tempore consequuntur, laudantium illo optio mollitia reprehenderit eos? Vel enim reprehenderit, quod eius itaque explicabo dolorem dolor veritatis corporis modi dolores facilis perspiciatis voluptas tenetur cum vero!
                Laborum temporibus amet minima, repellendus est deleniti rem labore nemo rerum suscipit, ratione, corrupti facere? Voluptas quaerat reprehenderit saepe nesciunt eaque, ex provident. Eos blanditiis, eum dolores accusamus voluptas inventore?
                Corrupti pariatur omnis reprehenderit! Ipsam, repudiandae tempore molestias commodi animi sunt harum placeat voluptates alias dicta minus similique delectus eos id ea voluptas odio illum esse rem, nemo explicabo excepturi.
                Sapiente voluptatibus odit voluptas ad et pariatur ullam velit, rerum adipisci illo earum ea mollitia laboriosam! Deserunt inventore, nemo, officiis recusandae, in sunt officia nisi itaque illo iste perspiciatis modi?
                Voluptas fuga eius maiores debitis aperiam? Nisi iusto recusandae itaque error magni nihil porro molestiae hic accusantium fuga? Totam adipisci nisi exercitationem odio necessitatibus placeat est illum suscipit quia enim?
                Dolores, minus? Quod iusto temporibus recusandae labore facilis, dolor vitae inventore facere cum repellat, qui corporis vel numquam minima officiis sunt. Laborum laboriosam nesciunt temporibus unde beatae at voluptate asperiores.
                Omnis ullam, repellat ad provident eaque eum quaerat ipsa ipsam beatae ducimus! Commodi velit, id possimus repellendus doloribus ducimus repudiandae! Laboriosam itaque velit, est quaerat saepe eius pariatur beatae consequuntur.
                Doloribus fuga nesciunt sed minima quam facere ex dolorum est exercitationem quisquam et tenetur at nulla quidem corrupti temporibus laboriosam, dolorem similique dolores odio. Id praesentium incidunt dignissimos hic voluptatem.
                Eligendi fuga qui, est soluta iusto perferendis cupiditate nulla quam animi eum quisquam neque adipisci consequuntur recusandae officiis labore dignissimos nihil error eos rerum quae blanditiis obcaecati sint numquam? Sit.
                Alias nemo qui tempore iste magni iure molestiae neque! Velit aperiam ducimus odio enim nemo veniam cupiditate ad possimus maiores quo quae blanditiis reiciendis quaerat, obcaecati quam dolorem, itaque ex!
                Error, minus est? Cum repellat consequatur earum ullam magni laborum hic minus, doloremque debitis quam quo voluptatibus eveniet voluptates, ducimus eaque voluptatem. Quidem cum tempora ea similique veritatis nesciunt eligendi.
                Minus eius sunt obcaecati doloribus, laboriosam asperiores ea blanditiis eos provident iste officiis tempore, dolorum necessitatibus explicabo magnam atque eum laudantium veniam dolore perferendis pariatur ab. Cupiditate id mollitia praesentium.
                Ad ex nemo nostrum, sapiente rerum ipsum maxime molestias quasi deserunt quis, nisi, praesentium minus. Quis cumque, sint dignissimos quidem consequatur eos atque velit voluptas repudiandae sit deleniti explicabo! Aut!
                Sed illum accusantium nobis impedit consequuntur eius exercitationem porro quibusdam deleniti ipsa suscipit quae eveniet, unde sapiente praesentium accusamus eos? In, architecto cupiditate. Deleniti impedit harum molestiae architecto delectus quod.
                Quis tempore laborum quo consequatur temporibus deleniti reiciendis sunt eveniet quibusdam minima, aperiam numquam doloremque alias. Est esse cumque laudantium fugiat. Velit magnam placeat facilis culpa ipsum, nam nostrum inventore.
                Quo laborum quibusdam qui enim tenetur tempore obcaecati molestias, culpa voluptates perspiciatis quia cum nemo libero odio fuga maxime officiis itaque cupiditate, ipsam placeat sunt? Impedit asperiores dolore dolores consequatur.
                Quidem mollitia exercitationem magnam fugit incidunt doloremque culpa, impedit expedita veritatis nulla illum, assumenda recusandae amet neque atque velit minus. Consequatur quidem inventore, facilis dignissimos a iure numquam blanditiis quibusdam?
                Magni nobis quod delectus provident. Deserunt pariatur earum commodi. Perferendis maxime natus, delectus dignissimos blanditiis explicabo iusto ab nemo recusandae, magnam quidem similique nobis nihil veniam quis nisi quaerat ratione!
                Quam quidem quod dolor ipsam temporibus deserunt incidunt repudiandae nostrum quia maxime iure nulla explicabo provident et, delectus minus inventore totam ipsa autem quis at, sint fuga modi praesentium. Modi!
                Quis perferendis repellendus dicta optio dolorum fugiat mollitia, qui obcaecati repudiandae illo ipsam nostrum officiis voluptate itaque blanditiis eius sapiente et ut illum officia placeat ducimus ipsum dolorem minima! Hic?
                Voluptate, commodi. Praesentium aut eum aperiam nesciunt pariatur minima ea perspiciatis, sunt nobis illo odit ipsa ducimus debitis! Ipsa laboriosam illum quam est, quasi excepturi explicabo autem asperiores ratione iure.
                Asperiores obcaecati facilis velit nostrum aliquid culpa quasi repellendus non rem labore, iure quo, iusto aliquam ratione distinctio, repellat voluptates. Vitae, nihil dicta ipsam porro temporibus ducimus a labore eum.
                Nam, voluptate quo consequatur tempora pariatur delectus neque aut iste enim, inventore ipsa aspernatur reprehenderit, possimus at adipisci. Cumque facilis itaque quidem, repudiandae minima quo delectus deleniti a maiores modi.
                Amet, inventore saepe? Facilis, corporis nisi! Qui architecto numquam inventore iusto tempore maxime esse odio quos repudiandae nihil velit excepturi fugit, quibusdam quisquam tenetur possimus facilis voluptatem. Aliquam, aspernatur perspiciatis!
                Accusantium, vel? Inventore accusamus, quisquam, nam saepe adipisci minus nemo repudiandae eos similique molestiae explicabo sit voluptatum reiciendis quaerat tempora animi eius. Recusandae ratione voluptate obcaecati asperiores animi quas expedita.
                A, ut quis, consectetur dolorem molestiae, nostrum rerum voluptatibus repellat placeat nulla quidem. Doloremque facere, minima cupiditate totam numquam voluptate quis earum ut ex fugit praesentium quae eveniet odio laboriosam!
                Aperiam, incidunt ratione consequuntur laudantium minus consequatur labore praesentium id omnis ad voluptatem cupiditate accusamus recusandae sit quidem. Minima quisquam ducimus itaque nisi sequi maxime vero hic alias nam atque?
                Modi id aut magni voluptas! Deleniti porro iste sequi aspernatur tempora mollitia asperiores quos sit facere officiis a eius similique error libero at neque nesciunt, accusantium sapiente doloribus amet! Suscipit?
                Dolorem aliquam unde quidem vero exercitationem eveniet iste aspernatur, nemo doloremque voluptatem nostrum! Impedit doloremque totam, blanditiis adipisci, quo id asperiores omnis neque ipsa sint est consequatur voluptatibus error beatae?
                Voluptates placeat accusantium voluptas corrupti debitis qui voluptate, nisi labore distinctio voluptatibus quam reiciendis odio. Eius maxime facere assumenda eos ducimus, tenetur recusandae quidem omnis, fuga perferendis a! Odit, tempora.
                Sed at omnis atque modi et. At aliquam repudiandae voluptas sapiente, eveniet soluta, a eos tenetur quam possimus eum iusto officiis saepe doloribus labore modi maxime facere. Fuga, illo quibusdam.
                Consequuntur velit veritatis quidem ipsum obcaecati magni, vitae dignissimos non, et nobis fugit tenetur pariatur eligendi provident at, placeat soluta nulla nesciunt. Quae magni aliquam quasi molestiae accusamus consequatur laborum!
                Debitis a libero consectetur id veritatis aliquam at. Aspernatur fuga dolorem accusantium excepturi debitis odio porro adipisci, pariatur in unde tenetur quaerat iste sed ut! Ex sint sapiente beatae explicabo.
                Nihil harum sed odit, similique et eaque esse asperiores veniam saepe impedit, officia veritatis ab modi debitis illo repellat qui dolore tempora minima velit exercitationem quo nam quasi! Facere, excepturi!
                Vel, nulla expedita totam necessitatibus consequuntur perspiciatis nihil, rem tempore asperiores mollitia dolorum blanditiis praesentium saepe quo nemo sint sit. Sequi fuga dolorum optio nam, ex ipsum ab necessitatibus excepturi!
                Cupiditate vero consequuntur dolores unde voluptatibus, vel aut sit aliquid nulla atque deserunt veniam. Veritatis dolorem nobis, aliquam maxime, explicabo eveniet corrupti adipisci deserunt, possimus consequuntur sapiente eos optio quidem.
                Tempore voluptatibus eum iste ducimus error minima sapiente tenetur accusamus doloribus! Consequuntur iure molestias necessitatibus praesentium nam qui illo illum, vel, pariatur, consectetur corrupti officiis voluptates aspernatur impedit quia sapiente?
                Cumque ipsa, explicabo, voluptatem tenetur corrupti optio iste sint et alias quasi aliquam? Ipsa, eaque modi recusandae distinctio iusto inventore, quis officia assumenda tempore est qui vel sed veniam voluptatem?
                Dolor corrupti repellat non ipsam nihil repellendus voluptatibus similique accusamus ducimus deserunt cum voluptatum, saepe, assumenda error expedita fuga qui asperiores delectus unde aperiam. Odio eveniet nulla optio illo beatae?
                <Goto_magazine text={text} to={to}/>
            </div>
        </div>
    )
}

export default Full_story_container
